title = "Bitmattz"
languageName = "English"
[params.author]
    name = "Matheus Bitencourt"
    image = "img/profile.jpg"
    headline = "Software Developer"
    bio = "Software developer with a passion for 3D printing and technology, constantly creating new projects"
    links = [
      { email = "mailto:bitencourt.a.matheus@gmail.com" },
      { github = "https://github.com/bitmattz" },
       { linkedin = "https://linkedin.com/in/matheus-bitencourt-araujo" },
    ]


colorScheme = "Sapphire"
