title = "Bitmattz"
languageName = "Portuguese"
[params.author]
name = "Matheus Bitencourt"
image = "img/profile.jpg"
headline = "Software Developer"
bio = "Programador apaixonado por impressão 3D e tecnologia, sempre criando novos projetos."
links = [
  { email = "mailto:bitencourt.a.matheus@gmail.com" },
  { github = "https://github.com/bitmattz" },
   { linkedin = "https://linkedin.com/in/matheus-bitencourt-araujo" },
]

colorScheme = "Sapphire"
